spring:
  application:
    name: springboot-mybatis-quickstart
  #配置数据库连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/web
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: QQ666666


mybatis:
  configuration:
    #配置mybatis的日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl